apiVersion: integrations.flux/v1
kind: FluxHelmResource
metadata:
  name: my-fluxhelmresource
  namespace: flux
spec:
  customizations:
    - name: image
      value: "{{ .Values.nginx.image }}"
      type: string
    - name: image-tag
      value: "{{ .Values.nginx.image.version }}"
      type: string
status:
  state: good
  message: "Hello World"